-- Deprecated helper kept for reference.
-- Use the canonical migration instead:
-- supabase/migrations/202606300001_harden_chat_schema.sql
--
-- That migration creates:
-- - public.chats
-- - public.messages
-- - public.subscriptions
-- - public.usage_events
--
-- It also removes the old permissive "Allow All on subscriptions" policy.
